version: '3.9'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    command: ['/wait-for', 'mysql:3306', '--', 'npm', 'run', 'start:prod']
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: asdf1234
      MYSQL_DATABASE: 'diagnostic-modality-integration'
