name: Deploy to Azure

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  REGISTRY_NAME: nominaldevacr
  APP_NAME: dmi-api

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push to ACR
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@main
      - uses: tenhaus/get-release-or-tag@v2
        id: tag
      - name: Build Docker images
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ steps.tag.outputs.tag }} --target production --build-arg GHP_TOKEN=${{ secrets.GHP_TOKEN }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ steps.tag.outputs.tag }}

  dispatch-event:
    runs-on: ubuntu-latest
    name: Notify deploy workflow
    needs: build
    steps:
      - name: Dispatch dmi-api-updated event to nominal-systems/dmi
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: nominal-systems/dmi
          event-type: ${{ env.APP_NAME }}-updated
          client-payload: '{ "image": "${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ needs.build.outputs.tag }}" }'
