name: Build and Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: dmi-api
  AWS_ACCOUNT_ID: 216821345641

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Build and Push Docker Image to ECR
        uses: kciter/aws-ecr-action@v4
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ env.AWS_ACCOUNT_ID }}
          repo: ${{ env.DOCKER_IMAGE_NAME }}
          region: us-east-1
          tags: latest,${{ github.sha }}
          extra_build_args: "--target production --build-arg GHP_TOKEN=${{ secrets.GHP_TOKEN }}"
      - name: Dispatch api-updated event to nominal-systems/dmi
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: nominal-systems/dmi
          event-type: api-updated
          client-payload: '{ "image": "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}" }'
