name: Bundle Admin UI

on:
  workflow_dispatch:

env:
  API_URL: ''
  UI_URL: '/ui'

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.NOMINAL_AGENT_APP_ID }}
          private-key: ${{ secrets.NOMINAL_AGENT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Check out Admin UI code
        uses: actions/checkout@v4
        with:
          repository: nominal-systems/dmi-api-admin-ui
          ref: issues/4
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Build Admin UI
        run: API_URL=${{ env.API_URL }} UI_URL=${{ env.UI_URL }} npm run build
