name: Bundle Admin UI

on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.NOMINAL_AGENT_APP_ID }}
          private-key: ${{ secrets.NOMINAL_AGENT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Check out Admin UI code
        uses: actions/checkout@v4
        with:
          repository: nominal-systems/dmi-api-admin-ui
          ref: issues/4
          token: ${{ steps.generate_token.outputs.token }}
